<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'file preview and multiple file upload' => 'олдиндан кўриш ва бир нечта файлларни юклаш',
    'Note:' => 'Изоҳ:',
    'multiple file upload' => 'бир нечта файлни юклаш',
    'Your browser does not support {validation}. Try an alternative or more recent browser to access these features.' => 'Сизнинг браузерингиз {validation} -ни қўллаб-қувватламайди. Ушбу хусусиятларга кириш учун янги браузер версиясини ёки бошқа браузерни синаб кўринг.'
];
